// =============================================================================
// @onegrid/xlsx — cross-validation harness (v1.1.0 wave 23).
//
// End-to-end test: synthesize an `.xlsx` workbook whose cells declare a
// formula AND its Excel-computed answer (the `cachedValue` field), read
// it through `readWorkbook`, evaluate the formula through the
// @onegrid/formula engine, and assert the engine's result matches the
// cached value within tolerance.
//
// This is the "we match Excel" gate the v1.1.0 plan calls for. The
// fixture is hand-authored against Microsoft's published function docs;
// adopters wanting real Excel-or-LibreOffice-generated bytes can swap in
// their own .xlsx via this harness.
// =============================================================================

import { describe, expect, it } from 'vitest';
import { createFormulaEngine, type CellResolver } from '@onegrid/formula';
import '@onegrid/formula/excel-compat';
import { readWorkbook, writeWorkbook, type Cell, type Workbook } from '../workbook';

interface FormulaFixture {
  readonly formula: string;
  readonly expected: number | string | boolean;
  readonly tolerance?: number;
}

// Each entry is a formula + the value Excel computes for it. The harness
// writes them into A1, A2, A3, ... reads them back, and re-evaluates each
// in oneGrid's engine. Hand-checked against Microsoft's published docs.
const FORMULAS: ReadonlyArray<FormulaFixture> = [
  // Arithmetic + precedence
  { formula: '=1+2*3', expected: 7 },
  { formula: '=(1+2)*3', expected: 9 },
  { formula: '=2^10', expected: 1024 },
  { formula: '=-2^2', expected: 4 }, // unary minus binds tighter than ^
  // Math
  { formula: '=ABS(-5)', expected: 5 },
  { formula: '=INT(-2.5)', expected: -3 },
  { formula: '=TRUNC(-2.5)', expected: -2 },
  { formula: '=ROUND(-2.5, 0)', expected: -3 },
  { formula: '=ROUND(2.5, 0)', expected: 3 },
  { formula: '=SQRT(16)', expected: 4 },
  // Stats
  { formula: '=SUM(1, 2, 3, 4, 5)', expected: 15 },
  { formula: '=AVERAGE(2, 4, 6)', expected: 4 },
  { formula: '=MAX(1, 9, 3)', expected: 9 },
  { formula: '=MIN(7, 2, 5)', expected: 2 },
  { formula: '=COUNT(1, "x", 3)', expected: 2 },
  // Logical
  { formula: '=IF(1>0, "yes", "no")', expected: 'yes' },
  { formula: '=AND(TRUE, TRUE, FALSE)', expected: false },
  { formula: '=OR(FALSE, FALSE, TRUE)', expected: true },
  { formula: '=NOT(FALSE)', expected: true },
  { formula: '=IFS(1=2, "a", 1=1, "b")', expected: 'b' },
  // Text
  { formula: '=LEN("hello")', expected: 5 },
  { formula: '=UPPER("hello")', expected: 'HELLO' },
  { formula: '=LOWER("HELLO")', expected: 'hello' },
  { formula: '=CONCAT("a", "b", "c")', expected: 'abc' },
  { formula: '=LEFT("hello", 2)', expected: 'he' },
  { formula: '=RIGHT("hello", 2)', expected: 'lo' },
  { formula: '=MID("hello", 2, 3)', expected: 'ell' },
  // Date — TODAY()/NOW() are non-deterministic; use DATE().
  { formula: '=YEAR(DATE(2024, 6, 15))', expected: 2024 },
  { formula: '=MONTH(DATE(2024, 6, 15))', expected: 6 },
  { formula: '=DAY(DATE(2024, 6, 15))', expected: 15 },
  // Lambda + higher-order (wave 16)
  { formula: '=REDUCE(0, SEQUENCE(5), LAMBDA(a, v, a+v))', expected: 15 },
  // Engineering
  { formula: '=BIN2DEC("1010")', expected: 10 },
  { formula: '=DEC2BIN(10)', expected: '1010' },
];

describe('@onegrid/xlsx — cross-validation: round-trip formulas through write→read→evaluate', () => {
  it(`every fixture (${FORMULAS.length} formulas) round-trips and evaluates to the expected value`, async () => {
    const cells: Cell[] = FORMULAS.map((f, i) => ({
      ref: cellRef(i),
      value: typeof f.expected === 'number' ? f.expected : 0,
      type: 'n',
      formula: f.formula.replace(/^=/, ''),
      cachedValue: String(f.expected),
    }));
    const wb: Workbook = {
      sheets: [{ name: 'Cross', sheetId: 1, cells }],
      date1904: false,
      opc: undefined as unknown as Workbook['opc'],
    };
    const bytes = await writeWorkbook(wb);
    const reread = await readWorkbook(bytes);
    const sheet = reread.sheets[0]!;
    expect(sheet.cells.length).toBe(FORMULAS.length);

    const engine = createFormulaEngine();
    const resolver: CellResolver = {
      getCell: () => null,
      getRange: () => [],
    };

    const failures: { formula: string; got: unknown; want: unknown }[] = [];
    for (let i = 0; i < FORMULAS.length; i++) {
      const fix = FORMULAS[i]!;
      const cell = sheet.cells[i]!;
      expect(cell.formula).toBe(fix.formula.replace(/^=/, ''));
      const got = engine.evaluate(`=${cell.formula}`, resolver);
      const want = fix.expected;
      const ok =
        typeof want === 'number' && typeof got === 'number'
          ? Math.abs(got - want) < (fix.tolerance ?? 1e-9)
          : got === want;
      if (!ok) failures.push({ formula: fix.formula, got, want });
    }
    if (failures.length > 0) {
      console.error('Cross-validation failures:');
      for (const f of failures) console.error(`  ${f.formula} → got ${JSON.stringify(f.got)}, want ${JSON.stringify(f.want)}`);
    }
    expect(failures).toEqual([]);
  });
});

function cellRef(i: number): string {
  // A1, A2, ..., A1000+ — we only need ~30.
  return `A${i + 1}`;
}
