// =============================================================================
// The schema model.
//
// This is the vocabulary every other module in the package speaks. Three
// decisions shape it:
//
// 1. **Descriptors are plain data.** No classes, no methods, no hidden
//    identity. A `DatabaseSchema` survives `structuredClone`, a `postMessage`
//    to a worker, and `JSON.stringify` to a cache — which matters because the
//    migration planner diffs two of these and a UI keeps one in a store.
//
// 2. **Descriptors carry what Postgres actually stores, not what a form
//    wants.** `defaultExpression` is the raw `pg_get_expr` text, not a parsed
//    value; `checkConstraint.expression` is the raw `pg_get_constraintdef`
//    body. Parsing is a lossy convenience, so it lives in `buildRowDefault`
//    where the loss is visible, not in the model where it would be silent.
//
// 3. **Column type is recorded twice, on purpose.** `dataType` is the
//    Postgres type name (`character varying(255)`, `public.mood`) and is what
//    DDL round-trips through. `columnType` is the protocol's `ColumnType`,
//    derived via `@onegrid/introspect`'s `columnTypeFromSql`, and is what a
//    renderer switches on. Neither can be reconstructed from the other
//    without losing something, so both are kept.
// =============================================================================

import type { ColumnType } from '@onegrid/protocol';

/** Where a column's value comes from when the client does not supply one.
 * @public
 */
export type ColumnIdentityKind = 'none' | 'always' | 'by default';

/** A column, as Postgres describes it.
 * @public
 */
export interface ColumnDescriptor {
  readonly name: string;
  /** Postgres type name including any modifier — `numeric(10,2)`,
   *  `timestamp with time zone`, `text[]`, `public.mood`. */
  readonly dataType: string;
  /** The protocol `ColumnType` a renderer switches on. */
  readonly columnType: ColumnType;
  readonly isNullable: boolean;
  /** Raw `pg_get_expr(adbin, adrelid)` text, or null when there is no
   *  default. Never pre-parsed — see the banner. */
  readonly defaultExpression: string | null;
  /** `GENERATED ALWAYS AS IDENTITY` / `GENERATED BY DEFAULT AS IDENTITY`. */
  readonly identity: ColumnIdentityKind;
  /** Body of a `GENERATED ALWAYS AS (...) STORED` column, or null. */
  readonly generatedExpression: string | null;
  readonly comment: string | null;
  /** 1-based `attnum`. Postgres never reuses these, and a dropped column
   *  leaves a hole, so this is not an array index. */
  readonly ordinalPosition: number;
  /** Set when `dataType` resolves to a user-defined enum, so a UI can offer
   *  a select instead of a text box without a second lookup. */
  readonly enumTypeName: string | null;
  readonly characterMaximumLength: number | null;
  readonly numericPrecision: number | null;
  readonly numericScale: number | null;
}

/** @public */
export interface PrimaryKeyDescriptor {
  readonly name: string;
  /** Ordered by key position — a compound key's order is load-bearing. */
  readonly column: readonly string[];
}

/** @public */
export interface UniqueConstraintDescriptor {
  readonly name: string;
  readonly column: readonly string[];
  /** True when the constraint is backed by a deferred unique index. */
  readonly isDeferrable: boolean;
}

/** @public */
export interface CheckConstraintDescriptor {
  readonly name: string;
  /** The body only — `pg_get_constraintdef` output with the surrounding
   *  `CHECK (...)` stripped. */
  readonly expression: string;
}

/** Referential action for a foreign key, spelled as Postgres spells it.
 * @public
 */
export type ForeignKeyAction =
  | 'cascade'
  | 'set null'
  | 'set default'
  | 'restrict'
  | 'no action';

/** @public */
export interface ForeignKeyDescriptor {
  readonly name: string;
  /** Referencing columns, in constraint key order. */
  readonly column: readonly string[];
  readonly referencedSchema: string;
  readonly referencedTable: string;
  /** Referenced columns, positionally paired with `column`. */
  readonly referencedColumn: readonly string[];
  readonly onDelete: ForeignKeyAction;
  readonly onUpdate: ForeignKeyAction;
}

/** @public */
export type IndexMethod = 'btree' | 'hash' | 'gin' | 'gist' | 'spgist' | 'brin';

/** @public */
export interface IndexDescriptor {
  readonly name: string;
  readonly method: IndexMethod;
  readonly isUnique: boolean;
  readonly isPrimary: boolean;
  /** Plain column names in index order. An expression index contributes an
   *  empty slot here and an entry in `expression` instead. */
  readonly column: readonly string[];
  /** Expression bodies for expression indexes — `lower(email)`. */
  readonly expression: readonly string[];
  /** `WHERE` body of a partial index, or null. */
  readonly predicate: string | null;
  /** Full `pg_get_indexdef` text. Kept because reversing a `dropIndex`
   *  needs the exact definition and nothing less will reconstruct it. */
  readonly definition: string;
}

/** @public */
export type TriggerTiming = 'before' | 'after' | 'instead of';

/** @public */
export type TriggerEvent = 'insert' | 'update' | 'delete' | 'truncate';

/** @public */
export interface TriggerDescriptor {
  readonly name: string;
  readonly timing: TriggerTiming;
  readonly event: readonly TriggerEvent[];
  readonly orientation: 'row' | 'statement';
  readonly functionName: string;
  readonly isEnabled: boolean;
  readonly definition: string;
}

/** @public */
export type PolicyCommand = 'all' | 'select' | 'insert' | 'update' | 'delete';

/** @public */
export interface RlsPolicyDescriptor {
  readonly name: string;
  readonly command: PolicyCommand;
  /** PERMISSIVE (default, OR-ed) vs RESTRICTIVE (AND-ed). */
  readonly isPermissive: boolean;
  /** Roles the policy applies to. `['public']` means everyone. */
  readonly role: readonly string[];
  readonly usingExpression: string | null;
  readonly withCheckExpression: string | null;
}

/** @public */
export type RelationKind = 'table' | 'view' | 'materialized view' | 'foreign table' | 'partitioned table';

/** A table (or view) and everything attached to it.
 * @public
 */
export interface TableDescriptor {
  readonly schema: string;
  readonly name: string;
  readonly kind: RelationKind;
  readonly comment: string | null;
  readonly isRlsEnabled: boolean;
  readonly column: readonly ColumnDescriptor[];
  readonly primaryKey: PrimaryKeyDescriptor | null;
  readonly uniqueConstraint: readonly UniqueConstraintDescriptor[];
  readonly checkConstraint: readonly CheckConstraintDescriptor[];
  readonly foreignKey: readonly ForeignKeyDescriptor[];
  readonly index: readonly IndexDescriptor[];
  readonly trigger: readonly TriggerDescriptor[];
  readonly policy: readonly RlsPolicyDescriptor[];
  /** `pg_class.reltuples` — the planner's estimate, negative-normalised to
   *  0 when the table has never been analysed. Risk assessment leans on
   *  this; it is an estimate and is documented as one. */
  readonly estimatedRowCount: number;
}

/** @public */
export interface EnumTypeDescriptor {
  readonly schema: string;
  readonly name: string;
  /** Labels in sort order (`enumsortorder`), not insertion order. */
  readonly label: readonly string[];
}

/** @public */
export interface ViewDescriptor {
  readonly schema: string;
  readonly name: string;
  readonly isMaterialized: boolean;
  /** `pg_get_viewdef` body. */
  readonly definition: string;
  readonly column: readonly ColumnDescriptor[];
}

/** @public */
export interface SequenceDescriptor {
  readonly schema: string;
  readonly name: string;
  readonly dataType: string;
  readonly startValue: string;
  readonly incrementBy: string;
  readonly minValue: string | null;
  readonly maxValue: string | null;
  readonly isCycled: boolean;
  /** Set when the sequence is owned by a serial/identity column. Dropping
   *  such a sequence directly is an error; drop the column instead. */
  readonly ownedByTable: string | null;
  readonly ownedByColumn: string | null;
}

/** The whole introspected database, as one serialisable value.
 * @public
 */
export interface DatabaseSchema {
  readonly schemaName: readonly string[];
  readonly table: readonly TableDescriptor[];
  readonly view: readonly ViewDescriptor[];
  readonly enumType: readonly EnumTypeDescriptor[];
  readonly sequence: readonly SequenceDescriptor[];
}

/** A `schema.table` pair. Used wherever a function takes a relation by
 *  reference rather than by descriptor.
 * @public
 */
export interface TableRef {
  readonly schema: string;
  readonly name: string;
}

/** A compiled statement plus its bind parameters. DDL always compiles with
 *  an empty `param` — see the `identifier.ts` banner for why.
 * @public
 */
export interface CompiledStatement {
  readonly sql: string;
  readonly param: readonly unknown[];
}

/**
 * Minimal query interface the studio runs over. Deliberately identical in
 * shape to `SqliteQueryable` in `@onegrid/sqlite` so an adopter who has
 * already written one adapter recognises this one. Any Postgres driver
 * satisfies it in three lines:
 *
 * ```ts
 * const queryable = { query: (sql, param) => pool.query(sql, param ?? []).then((r) => r.rows) };
 * ```
 * @public
 */
export interface PostgresQueryable {
  query(
    sql: string,
    param?: readonly unknown[],
  ):
    | readonly Record<string, unknown>[]
    | Promise<readonly Record<string, unknown>[]>;
}

/** Look a table up by schema-qualified name. Returns null rather than
 *  throwing, because a UI asks about tables that may have been dropped by
 *  someone else since the last introspection.
 * @public
 */
export function findTable(
  schema: DatabaseSchema,
  ref: TableRef,
): TableDescriptor | null {
  return (
    schema.table.find((t) => t.schema === ref.schema && t.name === ref.name) ?? null
  );
}

/** Look a column up on a table. Null when absent.
 * @public
 */
export function findColumn(
  table: TableDescriptor,
  name: string,
): ColumnDescriptor | null {
  return table.column.find((c) => c.name === name) ?? null;
}

/** Render a `TableRef` as `schema.name` for keys, maps and messages. Not a
 *  SQL identifier — use `qualifiedIdentifier` for that.
 * @public
 */
export function tableKey(ref: TableRef): string {
  return `${ref.schema}.${ref.name}`;
}

/** True when the column can never be supplied by a client INSERT — an
 *  identity column declared ALWAYS, or a stored generated column. Both
 *  `buildRowDefault` and `duplicateRow` exclude these.
 * @public
 */
export function isColumnWriteBlocked(column: ColumnDescriptor): boolean {
  return column.identity === 'always' || column.generatedExpression !== null;
}
